# Generated by Django 4.1.3 on 2022-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('money_transfer_create', models.DateTimeField(auto_now_add=True)),
                ('money_transfer_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
