# Generated by Django 4.1.3 on 2022-12-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazebank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Mazebank_users',
        ),
    ]
