# Generated by Django 4.1.3 on 2022-12-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazebank', '0002_rename_bank_mazebank_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mazebank_users',
            new_name='Users',
        ),
    ]
