# Generated by Django 4.1.3 on 2022-12-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazebank', '0003_rename_mazebank_users_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ЧеловекОшибка', max_length=255)),
                ('cards', models.CharField(default=None, max_length=255)),
                ('balance_debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_credit', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('money_transfer_create', models.DateTimeField(auto_now_add=True)),
                ('money_transfer_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='money_transfer_create',
        ),
        migrations.RemoveField(
            model_name='users',
            name='money_transfer_update',
        ),
        migrations.RemoveField(
            model_name='users',
            name='title',
        ),
        migrations.AddField(
            model_name='users',
            name='activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='client', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='ЧеловекОшибка', max_length=255),
        ),
    ]
