# Generated by Django 4.1.3 on 2022-12-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazebank', '0004_client_remove_users_money_transfer_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='money_transfer_create',
        ),
        migrations.RemoveField(
            model_name='client',
            name='money_transfer_update',
        ),
    ]
